apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer  # Exposes the service externally using a cloud provider’s load balancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: myapp
